### ISSUE TITLE
Port to attrs version >=21.4

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#377]
There is a dependabot PR https://github.com/bo4e/BO4E-python/pull/297 which updates attrs to v21.4.
This version brings a lot of redability improvements of the attrs-API.

We should use these improvements here.

Namely the changes include:
- `attrs.define` instead of `attr.s`
- `attrs.field` instead of `attr.ib`
- `attrs.validators` instead of `attr.validators`

## Todo:
In a fork of this repo:
- [x] Switch to the new API
- [ ] Make sure all the CI actions still pass
- [ ] Open a PR to this repository

(You can check a similar change [here](https://github.com/Hochfrequenz/mig_ahb_utility_stack/commit/8c30dcbf13a05cdc6112ed3d14a29549af6cbbe7)).
